import type { BiddingColumnDefinition } from "./biddingQuery.types";

export const biddingColumns: BiddingColumnDefinition[] = [
  { id: "tipo_documento", label: "Tipo Documento", active: true },
  { id: "municipality_name", label: "Municipio", active: true },
  { id: "cod_municipio", label: "Codigo do Municipio", active: false },
  { id: "numero_processo", label: "Numero Processo", active: true },
  { id: "especie_processo", label: "Especie Processo", active: true },
  { id: "objeto", label: "Objeto", active: true },
  { id: "valor_estimado", label: "Valor Estimado", active: true },
  { id: "modalidade", label: "Modalidade", active: true },
  { id: "criterio_julgamento", label: "Criterio Julgamento", active: true },
  { id: "data_autuacao", label: "Data Autuacao", active: true },
  { id: "data_portaria_comissao", label: "Portaria Comissao", active: false },
  { id: "sequencial_comissao", label: "Sequencial Comissao", active: false },
  { id: "cpf_parecer_juridico", label: "CPF Parecer Juridico", active: false },
  { id: "nome_parecer_juridico", label: "Nome Parecer Juridico", active: false },
  { id: "cpf_gestor_unidade", label: "CPF Gestor Unidade", active: false },
  { id: "cpf_homologacao", label: "CPF Homologacao", active: false },
  { id: "nome_homologacao", label: "Nome Homologacao", active: false },
  { id: "data_homologacao", label: "Data Homologacao", active: false },
  { id: "hora_realizacao", label: "Hora Realizacao", active: false },
  { id: "data_realizacao", label: "Data Realizacao", active: false },
  { id: "valor_limite_superior", label: "Valor Limite Superior", active: false },
  { id: "justificativa_preco", label: "Justificativa Preco", active: false },
  { id: "motivo_escolha_fornecedor", label: "Motivo Escolha Fornecedor", active: false },
  { id: "fundamentacao_legal", label: "Fundamentacao Legal", active: false },
  { id: "orgao_gerenciador_ata", label: "Orgao Gerenciador Ata", active: false },
  { id: "data_referencia", label: "Data Referencia", active: false },
  { id: "cpf_cotacao_precos", label: "CPF Cotacao Precos", active: false },
  { id: "nome_cotacao_precos", label: "Nome Cotacao Precos", active: false },
  { id: "cpf_elaborador_termo", label: "CPF Elaborador Termo", active: false },
  { id: "nome_elaborador_termo", label: "Nome Elaborador Termo", active: false },
  { id: "forma_contratacao", label: "Forma Contratacao", active: false },
  { id: "tipo_disputa", label: "Tipo Disputa", active: false },
  { id: "url_plataforma", label: "URL Plataforma", active: false },
  { id: "sistema_registro_preco", label: "Sistema Registro Preco", active: false },
  { id: "id_contratacao_pncp", label: "Id Contratacao PNCP", active: false },
  { id: "id_ata_pncp", label: "Id Ata PNCP", active: false },
];
