import type { ContratoColumnDefinition, ContratoFilters } from "./contractQuery.types";

export const contratoColumns: ContratoColumnDefinition[] = [
  { id: "tipo_documento", label: "Tipo Documento", active: true },
  { id: "municipality_name", label: "Municipio", active: true },
  { id: "cod_municipio", label: "Codigo do Municipio", active: false },
  { id: "cpf_gestor", label: "CPF Gestor", active: true },
  { id: "numero_contrato", label: "Numero", active: true },
  { id: "data_assinatura", label: "Data Assinatura", active: true },
  { id: "tipo_objeto", label: "Tipo Objeto", active: true },
  { id: "modalidade", label: "Modalidade", active: true },
  { id: "cpf_gestor_original", label: "CPF Gestor Original", active: false },
  { id: "numero_contrato_original", label: "Numero Contrato Original", active: false },
  { id: "data_contrato_original", label: "Data Contrato Original", active: false },
  { id: "vigencia_inicial", label: "Vigencia Inicial", active: true },
  { id: "vigencia_final", label: "Vigencia Final", active: true },
  { id: "data_inicio_obra", label: "Data Inicio Obra", active: false },
  { id: "tipo_obra_servico", label: "Tipo Obra/Servico", active: false },
  { id: "numero_obra", label: "Numero Obra", active: false },
  { id: "data_termino_obra", label: "Data Termino Obra", active: false },
  { id: "referencia", label: "Referencia", active: true },
  { id: "data_autuacao", label: "Data Autuacao", active: false },
  { id: "numero_processo", label: "Numero Processo", active: false },
  { id: "valor", label: "Valor", active: true },
  { id: "objeto_contrato", label: "Objeto", active: true },
  { id: "cpf_fiscal", label: "CPF Fiscal", active: true },
  { id: "nome_fiscal", label: "Nome Fiscal", active: true },
  { id: "id_contrato_pncp", label: "Id Contrato PNCP", active: false },
];

export const emptyFilters: ContratoFilters = {
  tipo_documento: "",
  municipality_name: "",
  cod_municipio: "",
  cpf_gestor: "",
  numero_contrato: "",
  data_assinatura: "",
  tipo_objeto: "",
  modalidade: "",
  cpf_gestor_original: "",
  numero_contrato_original: "",
  data_contrato_original: "",
  vigencia_inicial: "",
  vigencia_final: "",
  data_inicio_obra: "",
  tipo_obra_servico: "",
  numero_obra: "",
  data_termino_obra: "",
  referencia: "",
  data_autuacao: "",
  numero_processo: "",
  valor: "",
  objeto_contrato: "",
  cpf_fiscal: "",
  nome_fiscal: "",
  id_contrato_pncp: "",
};
